version: "3"
services:
  baleine-api:
    restart: always
    image: $HUB_URL:$TAG
    networks:
      - web
      - db
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - MONGO_URL=mongodb://mongo-dev:27017/baleinebot
      - API_URL=https://${HOST}
      - API_PORT=3636
        
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=3636
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}

networks:
  web:
    external: true
  db:
    external: true
