version: "3"
services:
  baleine-api:
    restart: always
    image: $HUB_URL:$TAG
    networks:
      - web
      - db
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - MONGO_URL=mongodb://mongo-dev:27017/baleinebot
      - API_URL=https://api.labaleine.gg
      - API_PORT=3636
        
      - VIRTUAL_HOST=api.labaleine.gg
      - VIRTUAL_PORT=3636
      - LETSENCRYPT_HOST=api.labaleine.gg
      - LETSENCRYPT_EMAIL=baleinefr@gmail.com

networks:
  web:
    external: true
  db:
    external: true
